#!/usr/local/bin/php
<?php
use Garden\Cli\Cli;

require_once("vendor/autoload.php");

// Define the cli options.
$cli = new Cli();

$cli->description('Import datasets into Niall.')
    ->opt('niall:n', 'Connect to niall instance.', false);

// Parse and return cli args.
$args = $cli->parse($argv, true);

ob_start();
$fp = readfile("php://stdin");
$input = ob_get_contents();
ob_get_clean();

$paragraphs = explode("\n", $input);
$paragraphs = array_filter($paragraphs);
$sentences = [];
foreach($paragraphs as $paragraph){
    $sentences = array_merge($sentences, explode(".", $paragraph));
}
$sentences = array_filter($sentences);

$client = new \GuzzleHttp\Client();

$newWords = 0;

echo "Got " . count($paragraphs) . " paragraphs and " . count($sentences) . " sentences. \n";
foreach(array_values($sentences) as $i => $sentence){
    echo "\rInjesting " . ($i+1) . " of " . count($sentences) . "...";
    $response = $client->request(
        'POST',
        $args->getOpt('niall', 'http://niall.chat') . "/v1/speak", [
        'json' => [
            'Message' => trim($sentence)
        ]
    ]);
    if(!$response->getStatusCode() == 200 || !$response->getHeader('content-type') == 'application/json') {
        echo $response->getBody();
        die("\n\nFailed to communicate with service. Response type was " . $response->getHeader('content-type') . "\n");
    }else{
        $jsonDecoded = json_decode($response->getBody());
        $newWords = $newWords + count($jsonDecoded->new_words);
    }
    usleep(0.1 * 1000000);
}

echo "\n\nComplete. Niall learned {$newWords} new words.\n";